id: I87F323D7
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T08:22:56+00:00'
last_modified: '2022-06-08T03:19:39.823914+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD83960
  title: གསུང་འབུམ། ཤེས་བྱ་ཀུན་རིག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    A544:
      image_group_id: I1PD84594
      title: ''
      total_pages: 670
      order: 1
      base_file: A544.txt
    BCDD:
      image_group_id: I1PD84595
      title: ''
      total_pages: 646
      order: 2
      base_file: BCDD.txt
    66D1:
      image_group_id: I1PD84596
      title: ''
      total_pages: 710
      order: 3
      base_file: 66D1.txt
    A09A:
      image_group_id: I1PD84597
      title: ''
      total_pages: 678
      order: 4
      base_file: A09A.txt
    F280:
      image_group_id: I1PD84598
      title: ''
      total_pages: 702
      order: 5
      base_file: F280.txt
    3EA1:
      image_group_id: I1PD84599
      title: ''
      total_pages: 718
      order: 6
      base_file: 3EA1.txt
    A4AB:
      image_group_id: I1PD84600
      title: ''
      total_pages: 654
      order: 7
      base_file: A4AB.txt
    C757:
      image_group_id: I1PD84601
      title: ''
      total_pages: 646
      order: 8
      base_file: C757.txt
    75EF:
      image_group_id: I1PD84602
      title: ''
      total_pages: 646
      order: 9
      base_file: 75EF.txt
    7E77:
      image_group_id: I1PD84603
      title: ''
      total_pages: 566
      order: 10
      base_file: 7E77.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
