id: P005472
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD83960
  title: གསུང་འབུམ། ཤེས་བྱ་ཀུན་རིག
  author: ''
  volumes:
    8b651ff59d8f40c08aaca2c60af86584:
      image_group_id: I1PD84594
      title: ''
      volume_number: 1
      total_pages: 670
    6f6d8c4ee88747deaf21c5e98f3495ac:
      image_group_id: I1PD84595
      title: ''
      volume_number: 2
      total_pages: 646
    25e8e08affd5460fa8d1fa9330dadcf9:
      image_group_id: I1PD84596
      title: ''
      volume_number: 3
      total_pages: 710
    1ec1d561f3304d0595563d261d0f0271:
      image_group_id: I1PD84597
      title: ''
      volume_number: 4
      total_pages: 678
    3e39a21bb59b46a486fb53e193527186:
      image_group_id: I1PD84598
      title: ''
      volume_number: 5
      total_pages: 702
    582744149ff04fa89d36a8cb7751a09b:
      image_group_id: I1PD84599
      title: ''
      volume_number: 6
      total_pages: 718
    78e36cfefa3048248b823acf24c4821d:
      image_group_id: I1PD84600
      title: ''
      volume_number: 7
      total_pages: 654
    558532254a6848479861f9a03cf27f91:
      image_group_id: I1PD84601
      title: ''
      volume_number: 8
      total_pages: 646
    5f9eb0377e434c518e6bd1cb9d3bd05d:
      image_group_id: I1PD84602
      title: ''
      volume_number: 9
      total_pages: 646
    66d9ab0021864535a3ca32b5f24f9dc3:
      image_group_id: I1PD84603
      title: ''
      volume_number: 10
      total_pages: 566
